# Generated by Django 4.1.7 on 2023-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=20)),
                ('Patronym', models.CharField(max_length=20)),
                ('Date_of_birth', models.DateField(default='02.02.2000')),
                ('Date_of_employment', models.DateField(auto_now=True)),
                ('Shift', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.BooleanField(default=False)),
                ('Surname', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=20)),
                ('Patronym', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=9, unique=True)),
                ('E_mail', models.CharField(max_length=30, unique=True)),
                ('Postal_adders', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_code', models.IntegerField()),
                ('Payment_method', models.IntegerField()),
                ('Order_date', models.DateField(auto_now=True)),
                ('Delivery_date', models.DateField()),
                ('Delivery_type', models.IntegerField()),
                ('Delivery_price', models.FloatField()),
                ('Courier_code', models.IntegerField()),
                ('Delivery_adders', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=255)),
                ('Characteristic', models.TextField(blank=True)),
                ('Country', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
