# Generated by Django 4.1.7 on 2023-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['Type', 'Price'], 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Organization',
        ),
        migrations.AddField(
            model_name='customer',
            name='Password',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='Date_of_birth',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Characteristic',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Company',
            field=models.CharField(max_length=255, verbose_name='Компания производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Country',
            field=models.CharField(max_length=50, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
    ]
